sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
  -
script:
  - python3 for f in *.py; do echo "$f"; python3 "$f"; done
notifications:
  email:
    on_success: never
